---
# vars file for add-hermes-service
required_packages:
- python3.6
- python3-pip
- python3-venv
- python3.6-venv
- python3-setuptools
- python-setuptools
- sshpass
- autossh
- zip
- git
pip_packages:
- virtualenv
- setuptools