---

- name: install required packages
  apt:
    name: "{{ required_packages }}"
    update_cache: yes
  ignore_errors: True
  register: python36_notfound

- name: add python3.6 repo if install failed
  apt_repository:
    repo: ppa:deadsnakes/ppa
    update_cache: yes
  when: python36_notfound != 0
  register: python36_repo_add

- name: install required packages when add repository
  apt:
    name: "{{ required_packages }}"
    update_cache: yes
  when: python36_repo_add is succeeded

- name: get src from git
  git:
    repo: https://github.com/404notfoundhard/autotunnel.git
    dest: /tmp/ansible-tmp/autotunnel/
    
- name: Copy src web-server
  copy:
    src: /tmp/ansible-tmp/autotunnel/web-server/
    dest: /srv/web-server
    mode: u=rw,g=r
    remote_src: yes
  notify:
  - Restart hermes and reload daemon

- name: dev locale
  action: command sudo update-locale LC_ALL=en_US.UTF-8

- name: set default locale
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: create log folder
  file:
    path: "{{web_log_path}}"
    state: directory

- name: Install virtualenv via pip
  pip:
    name: "{{pip_packages}}"
    executable: pip3

- name: create python virtual environment and install requirements
  pip:
     requirements: /srv/web-server/requirements.txt
     virtualenv: /srv/web-server/venv
     virtualenv_python: python3.6

- name: copy hermes.service
  template:
    dest: /etc/systemd/system/hermes.service
    src: hermes.service.j2
    owner: root
    group: root
  notify:
  - Restart hermes and reload daemon
