---
# handlers file for add-hephaestus-service
- name: Reload systemctl daemon
  systemd: 
    daemon_reload: yes

- name: Restart hephaestus and reload daemon
  systemd:
    daemon_reload: yes
    name: hephaestus
    state: restarted
