---
# tasks file for add-hephaestus-service
- name: Copy app in zip 
  copy:
    src: api-client.zip
    dest: /srv/api-client.zip
    owner: root
    group: root
    mode: u=rw,g=r
    remote_src: no

- name: dev locale
  action: command sudo update-locale LC_ALL=en_US.UTF-8

- name: set default locale
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: install unzip
  apt:
    name: zip
    update_cache: yes


- name: unzip api-client.zip
  unarchive:
      src: /srv/api-client.zip
      dest: /srv/
      remote_src: yes

- name: install python3.6 and python3.6-venv
  apt:
    name: "{{ required_packages }}"
    update_cache: yes
  ignore_errors: True
  register: python36_notfound

- name: add python3.6 repo if install failed
  apt_repository:
    repo: ppa:deadsnakes/ppa
    update_cache: yes
  when: python36_notfound != 0
  register: python36_repo_add

- name: install python3.6 and python3.6-venv when add repository
  apt:
    name: "{{ required_packages }}"
    update_cache: yes
  when: python36_repo_add is succeeded

- name: Install virtualenv via pip
  pip:
    name: "{{ pip_packages }}"
    executable: pip3

- name: create python virtual environment and install requirements
  pip:
     requirements: /srv/api-client/requirements.txt
     virtualenv: /srv/api-client/venv
     virtualenv_python: python3.6

# - name: create ssh-key
#   openssh_keypair:
#     owner: root
#     path: /root/.ssh/key

- name: copy hephaestus.service
  template:
    dest: /etc/systemd/system/hephaestus.service
    src: hephaestus.service.j2
    owner: root
    group: root
  notify:
  - Reload systemctl daemon
  - Restart hephaestus
