Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
      v.memory = 512
    end
    config.vm.define "web-server" do |app|
      app.vm.synced_folder ".", "/vagrant", disabled: true      
      app.vm.box = "ubuntu/xenial64"
      app.vm.hostname = "web-server"
      app.vm.network :private_network, ip: "10.10.10.90"
      app.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/create-env.yml"
      end
    end

    config.vm.define "api-server" do |app|
      app.vm.synced_folder ".", "/vagrant", disabled: true
      app.vm.box = "ubuntu/bionic64"
      app.vm.hostname = "api-server"
      app.vm.network :private_network, ip: "10.10.10.91"
      app.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/create-env.yml"
      end
    end

    config.vm.define "postgres" do |app|
      app.vm.synced_folder ".", "/vagrant", disabled: true
      app.vm.box = "ubuntu/xenial64"
      app.vm.hostname = "postgres"
      app.vm.network :private_network, ip: "10.10.10.92"
      app.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/create-env.yml"
      end
    end

    (1..2).each do |i|
      config.vm.define "server#{i+1}" do |app|
        app.vm.synced_folder ".", "/vagrant", disabled: true
        app.vm.box = "ubuntu/xenial64"
        app.vm.hostname = "test#{i+1}"
        app.vm.network :private_network, ip: "10.10.10.#{i+1}"
        app.vm.provision "ansible" do |ansible|
          ansible.playbook = "provision/create-env.yml"
        end
      end
    end
  end
  