version: '3.6'
services:
  postgresbd:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_bd:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      database_net:
        ipv4_address: 10.10.10.2
        aliases:
          - postgres_db
  adminer:
    image: adminer:latest
    depends_on: 
      - postgresbd
    ports:
      - 80:8080
    networks:
      database_net:
        ipv4_address: 10.10.10.3

volumes:
  postgres_bd:

networks:
  database_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24